Support SNI when connecting to remote irods server
irods/irods pull request #5831
Opened 2021-09-07 18:32 UTC by peterverraedt

Add SNI support to outgoing irods connections. This makes icommands and
irods behave as the python client and jargon applications such as
metalnx. It allows for advanced proxy setups.

Signed-off-by: Peter Verraedt <peter.verraedt@kuleuven.be>

2021-09-07 19:09 UTC, korydraughn commented
Hi Peter, please open an issue and prepend the issue number (without the **#** symbol) to your commit message. This helps us keep track of things in a clean way.

For example, if the issue number is `1234`, then your commit message should look like the following until the PR is approved:
```bash
[1234] Support SNI when connecting to remote irods server ...
```

2021-09-08 06:45 UTC, peterverraedt commented
Fixes #5832

2021-09-20 21:56 UTC, alanking requested changes
All of my information came from these docs, so let me know if there's something else I should be looking at: https://www.openssl.org/docs/man1.1.1/man3/SSL_set_tlsext_host_name.html

Sorry about that delay!

2021-09-20 21:57 UTC, alanking commented on plugins/network/ssl/libssl.cpp
> +                if ( !( result = ASSERT_ERROR( status, SSL_INIT_ERROR, err_str.c_str() ) ).ok() ) {
...and by "remove the else case" I of course mean that the else block can just be dedented by 1, not deleted. :) Sorry

2021-09-21 09:03 UTC, peterverraedt commented on lib/core/src/sslSockComm.cpp
> +    status = SSL_set_tlsext_host_name( rcComm->ssl, rcComm->host );
Right, misread that part of the documentation.

2021-09-23 14:05 UTC, trel commented
A helpful page:  https://www.cloudflare.com/learning/ssl/what-is-sni/

2021-09-23 16:00 UTC, korydraughn approved these changes

2021-09-23 16:02 UTC, trel commented
Awesome - @peterverraedt please add the # to your commit message, and we'll merge it!   Then we'll cherry-pick to 4-2-stable.

2021-10-04 15:12 UTC, alanking approved these changes

2021-10-04 17:41 UTC, merged

2021-10-04 17:41 UTC, trel commented
Thanks @peterverraedt - sorry I didn't realize you had updated/pushed within 3h.